---
title: "Intro Reading & Introductions" 
subtitle: "ECI 586 Intro to Learning Analytics"
author: "Shaun Kellogg"
date: today
format:
  html:
    toc: true
    toc-depth: 3
theme: 
  light: cosmo
  dark: cyborg
---

As one of your first contributions to our learning community, I ask that you please introduce yourself to the class. To assist us with our introductions, please read **Chapter 1: Introduction** from our course text [Learning Analytics Goes to School](https://catalog.lib.ncsu.edu/catalog/NCSU4862134) prior to writing your introduction. An online version of this book is available at no cost through the NC State library. Please let me know if you have difficulty accessing this book.

In your introduction, please address the following if comfortable sharing:

1.  Your educational program and research area(s) of interest;

2.  What experience, if any, you've had with Learning Analytics as described in Chapter 1 and with data science/analysis tools like R and R RStudio;

3.  Any personal or professional learning goals and/or data sources you may be interested in working towards this semester;

4.  Any data sources you may be interested in exploring this semester;

5.  Three interesting and/or unusual facts about yourself, two of which are true and one of which is false.

After completing your introduction, please **respond to at least three of your peers** and see if you can guess which of their facts is complete fiction.  

Finally, if you haven't done so already, please **update your Moodle profile** with a picture and short bio.
